import { NavigatorScreenParams } from '@react-navigation/native';

export interface SelectedMaterial {
  id: string;
  name: string;
  price: number;
  qty: number;
  discountPct?: number;
}

export type WorkOrderPriority = 'Normal' | 'Yüksek' | 'Acil';
export type WorkOrderAssignmentStatus = 'Atanmadı' | 'Atandı' | 'Kabul Edildi' | 'Reddedildi' | 'Devredildi';

export interface WorkOrderTimeLog {
  id: string;
  startAt: string;
  endAt?: string;
  minutes?: number;
  userId?: string;
  note?: string;
}

export interface WorkOrder {
  id: string;
  client: string;
  serviceName: string;
  date: string;
  engineer: string;
  materials: SelectedMaterial[];
  otherCost: number;
  laborCost: number;
  materialCost: number;
  quoteAmount: number;
  profit: number;
  status:
    | 'Bekliyor'
    | 'Atandı'
    | 'Yolda'
    | 'Başladı'
    | 'Tamamlandı'
    | 'İptal'
    | 'Onay Bekliyor'
    | 'Teklif Gönderildi'
    | 'Faturalandırıldı';
  beforePhoto: string;
  afterPhoto: string;
  formPhoto?: string;
  notes: string;
  priority?: WorkOrderPriority;
  plannedStart?: string;
  plannedEnd?: string;
  slaHours?: number;
  assignedToId?: string;
  assignedToName?: string;
  assignmentStatus?: WorkOrderAssignmentStatus;
  rejectReason?: string;
  timeLogs?: WorkOrderTimeLog[];
  actualLaborMinutes?: number;
  videoUri?: string;
  audioUri?: string;
  signatureUri?: string;
  templateId?: string;
  customerId?: string;
  customerName?: string;
}

export interface Employee {
  id: string;
  name: string;
  role: string;
  monthlyWage: number;
  dailyRate: number;
  attendance: Record<string, string>;
  daysWorked: number;
}

export interface ToastMessage {
  message: string;
  type: 'success' | 'error';
}

export interface QuoteLine {
  lineNo: number;
  pozId: string;
  pozName: string;
  unit: string;
  quantity: number;
  materialPrice: number;
  installPrice: number;
  dismantlePrice: number;
  withDismantle: boolean;
  overheadPct: number;
  profitPct: number;
  vatPct: number;
  discountPct: number;
  notes?: string;
}

export type QuoteStatus = 'Taslak' | 'Onay Bekliyor' | 'Müşteriye Gönderildi' | 'Kabul Edildi' | 'Reddedildi' | 'Faturalandırıldı';

export interface Quote {
  id: string;
  number: string;
  customerName: string;
  customerTitle?: string;
  title: string;
  date: string;
  validUntil?: string;
  engineer: string;
  lines: QuoteLine[];
  status: QuoteStatus;
  notes?: string;
  subtotal: number;
  vatTotal: number;
  grandTotal: number;
  revision?: number;
  acceptedAt?: string;
  acceptedBy?: string;
  acceptSignature?: string;
  generatedWorkOrderId?: string;
  templateId?: string;
  shareToken?: string;
}

export interface Customer {
  id: string;
  shortName: string;
  title: string;
  taxNumber?: string;
  taxOffice?: string;
  phone?: string;
  email?: string;
  address?: string;
  city?: string;
  contactPerson?: string;
  type?: 'Potansiyel' | 'Aktif' | 'Pasif' | 'Bayi' | 'Tedarikçi';
  sector?: string;
  region?: string;
  assignedStaffId?: string;
  source?: string;
  riskLimit?: number;
  currentBalance?: number;
}

export type OrderStatus = 'draft' | 'submitted' | 'confirmed' | 'preparing' | 'shipped' | 'delivered' | 'cancelled';
export interface Order {
  id: string;
  code: string;
  customerId: string;
  customerName: string;
  orderDate: string;
  status: OrderStatus;
  total: number;
}

export type AssetType = 'meter' | 'panel' | 'transformer' | 'ges_inverter' | 'ges_panel' | 'compensation' | 'machine' | 'other';
export type EnergyReadingKind = 'meter' | 'panel' | 'transformer' | 'ges';
export type InspectionType = 'audit' | 'safety' | 'quality' | 'commissioning' | 'periodic';
export type NonconformityStatus = 'open' | 'in_progress' | 'closed' | 'cancelled';
export type TaskStatus = 'todo' | 'in_progress' | 'review' | 'done' | 'cancelled';
export type ProductItemStatus = 'in_stock' | 'in_use' | 'in_transit' | 'maintenance' | 'retired';
export type ApprovalStatus = 'pending' | 'approved' | 'rejected' | 'expired';
export type UserRoleExt = 'admin' | 'manager' | 'engineer' | 'field' | 'finance' | 'sales' | 'viewer';
export type PermissionResource = 'customer' | 'work_order' | 'quote' | 'task' | 'material' | 'vehicle' | 'payroll' | 'timesheet' | 'osos' | 'finance' | 'report' | 'user' | 'feedback' | 'crash' | 'release' | 'audit' | 'system';
export type OfflineOpStatus = 'pending' | 'syncing' | 'synced' | 'failed' | 'conflict';
export type ShareLinkResource = 'quote' | 'work_order' | 'report' | 'document';
export type SurveyStatus = 'draft' | 'sent' | 'completed' | 'declined';
export type VehicleLogKind = 'km' | 'fuel' | 'maintenance' | 'inspection' | 'insurance';
export type StockMovementKind = 'giris' | 'cikis' | 'transfer' | 'is-emri' | 'sayim';

// ============================================================
// STACK PARAMS
// ============================================================

export type AuthStackParamList = {
  Login: undefined;
  Signup: undefined;
  ForgotPassword: undefined;
  ResetPassword: { token?: string } | undefined;
};

export type FinanceStackParamList = {
  FinanceHub: undefined;
  Payments: { customerId?: string; workOrderId?: string } | undefined;
  PaymentForm: { paymentId?: string; customerId?: string; workOrderId?: string; quoteId?: string } | undefined;
  PaymentDetail: { paymentId: string };
  CustomerBalances: undefined;
  CashRegister: { employeeId?: string } | undefined;
  IncomeReport: undefined;
  AgingReport: undefined;
  EInvoice: undefined;
};

export type OperationStackParamList = {
  Shift: undefined;
  Geofences: undefined;
  CheckinScanner: undefined;
  NfcCheckin: undefined;
  Vehicles: undefined;
  VehicleForm: { vehicleId?: string } | undefined;
  VehicleDetail: { vehicleId: string };
  VehicleLogForm: { vehicleId: string; kind?: VehicleLogKind; logId?: string };
  VehicleLogs: { vehicleId?: string; kind?: VehicleLogKind } | undefined;
  VehicleDamages: { vehicleId?: string } | undefined;
  VehicleDamageForm: { vehicleId: string; damageId?: string };
  VehicleRoute: { vehicleId: string };
  Materials: undefined;
  MaterialForm: { materialId?: string } | undefined;
  Warehouses: undefined;
  WarehouseForm: { warehouseId?: string } | undefined;
  WarehouseDetail: { warehouseId: string };
  Stock: undefined;
  StockMovement: { kind?: StockMovementKind; materialId?: string; workOrderId?: string } | undefined;
  StockMovements: { materialId?: string; warehouseId?: string } | undefined;
};

export type CustomerStackParamList = {
  Customers: undefined;
  CustomerForm: { customerId?: string } | undefined;
  CustomerSites: { customerId: string };
  CustomerDocuments: { customerId: string };
  CustomerHistory: { customerId: string };
  JobRating: { workOrderId: string };
  CustomerPortal: { customerId: string };
  CustomerRatingsAll: undefined;
  CustomerHub: undefined;
  CustomerExperienceHub: undefined;
  PortalUsers: { customerId?: string } | undefined;
  PortalUserForm: { userId?: string; customerId?: string } | undefined;
  ShareLinks: { resource?: ShareLinkResource } | undefined;
  ShareLinkForm: { linkId?: string } | undefined;
  ShareLinkDetail: { linkId: string };
  SatisfactionSurveys: { status?: SurveyStatus } | undefined;
  SurveyDetail: { surveyId: string };
  CustomerNotificationPrefs: { customerId: string };
  AutoReports: undefined;
  AutoReportForm: { scheduleId?: string } | undefined;
};

export type RootStackParamList = {
  MainTabs: undefined;
  FinanceStack: NavigatorScreenParams<FinanceStackParamList>;
  OperationStack: NavigatorScreenParams<OperationStackParamList>;
  CustomerStack: NavigatorScreenParams<CustomerStackParamList>;
  Company: undefined;
  Expenses: undefined;
  Services: undefined;
  NewQuote: { quoteId?: string } | undefined;
  QuoteDetail: { quoteId: string };
  WorkOrderDetail: { workOrderId: string };
  Map: undefined;
  EmployeeDetail: { employeeId: string };
  LocationHistory: { userId: string; employeeName?: string };
  ChangePassword: undefined;
  BulkAssign: undefined;
  RecurringTasks: undefined;
  QuoteRevisions: { quoteId: string };
  QuoteAccept: { token: string };
  QuoteTemplates: undefined;
  FormTemplates: undefined;
  FormBuilder: { templateId?: string } | undefined;
  FormFill: { templateId: string; workOrderId?: string; responseId?: string };
  FormResponseDetail: { responseId: string };
  WorkOrderForms: { workOrderId: string };
  Assignments: undefined;
  BarcodeScan: { mode: 'material-lookup' | 'stock-in' | 'stock-out' };
  Reports: undefined;
  ReportDetail: { reportId: string };
  Dashboard: undefined;
  Sla: undefined;
  Notifications: undefined;
  NotificationPreferences: undefined;
  NotificationHub: undefined;
  NotificationStats: undefined;
  BroadcastMessage: undefined;
  Assets: { customerId?: string; type?: AssetType } | undefined;
  AssetForm: { assetId?: string; customerId?: string } | undefined;
  AssetDetail: { assetId: string };
  EnergyReadingForm: { readingId?: string; assetId?: string; kind?: EnergyReadingKind } | undefined;
  MaintenancePlans: { assetId?: string; customerId?: string } | undefined;
  Inspections: { assetId?: string; customerId?: string; type?: InspectionType } | undefined;
  InspectionForm: { inspectionId?: string; assetId?: string; type?: InspectionType } | undefined;
  Nonconformities: { assetId?: string; customerId?: string; status?: NonconformityStatus } | undefined;
  SalesVisits: { customerId?: string } | undefined;
  SectorHub: undefined;
  AssetHistory: undefined;
  SalesVisitForm: { visitId?: string; customerId?: string } | undefined;
  AiHub: undefined;
  AiAssistant: undefined;
  AiSettings: undefined;
  VisionScanner: undefined;
  VoiceNote: undefined;
  AiInsights: undefined;
  AdminShiftDashboard: undefined;
  ShiftHistory: undefined;
  ManagerCommandCenter: undefined;
  SmartPozSuggest: { description?: string } | undefined;
  PhotoAnalysis: { workOrderId?: string } | undefined;
  VoiceReport: { workOrderId?: string; customerId?: string } | undefined;
  RouteOptimizer: undefined;
  Anomalies: undefined;
  WebAdmin: undefined;
  UsersAdmin: undefined;
  UserApprovals: undefined;
  AllUsers: undefined;
  ExternalApiKeys: undefined;
  ScheduledEmails: undefined;
  LiveTracking: undefined;
  IntegrationsHub: undefined;
  ApiKeys: undefined;
  Webhooks: undefined;
  ExcelImport: undefined;
  ErpAdapters: undefined;
  Kvkk: undefined;
  Backup: undefined;
  TwoFactor: undefined;
  AccessRules: undefined;
  ConnectivityHub: undefined;
  AuditLog: undefined;
  SyncStatus: undefined;
  DataMigration: undefined;
  RoleMatrix: undefined;
  PersonnelTrackingHub: undefined;
  AttendanceReport: undefined;
  MockLocationAlerts: undefined;
  WorkOrderFlowHub: undefined;
  WorkOrderKanban: undefined;
  WorkOrderCostDashboard: undefined;
  AutoAssign: { workOrderId?: string } | undefined;
  QuoteFlowHub: undefined;
  QuoteEmail: { quoteId: string };
  QuoteShare: { quoteId: string };
  RecentPoz: undefined;
  FormHub: undefined;
  FormResponses: { templateId?: string; workOrderId?: string } | undefined;
  FormStats: undefined;
  StockHub: undefined;
  LowStockAlerts: undefined;
  StockSummary: undefined;
  VehicleHub: undefined;
  VehicleAlerts: undefined;
  VehicleFuelStats: undefined;
  ReportingHub: undefined;
  KpiOverview: undefined;
  ReportComparison: undefined;
  ProposalsHub: undefined;
  TransformerProposals: undefined;
  TransformerProposalForm: { quoteId?: string; customerId?: string } | undefined;
  GesProposals: undefined;
  GesProposalForm: { quoteId?: string; customerId?: string } | undefined;
  TaskHub: undefined;
  Tasks: { status?: TaskStatus; assignedTo?: string } | undefined;
  TaskForm: { taskId?: string } | undefined;
  TaskKanban: undefined;
  FuelReport: undefined;
  InventoryHub: undefined;
  ProductItems: { status?: ProductItemStatus; customerId?: string } | undefined;
  ProductItemForm: { itemId?: string } | undefined;
  ProductItemDetail: { itemId: string };
  ProductCatalog: undefined;
  OsosHub: undefined;
  OsosReadings: { customerId?: string } | undefined;
  OsosImport: undefined;
  WeeklyReports: undefined;
  WeeklyReportDetail: { reportId: string };
  PayrollHub: undefined;
  Timesheet: { employeeId?: string; month?: string } | undefined;
  PayrollRuns: { month?: string } | undefined;
  PayrollDetail: { runId: string };
  Profile: undefined;
  TaskDetail: { taskId: string };
  TaskAnalytics: undefined;
  Calendar: { month?: string } | undefined;
  CalendarEventForm: { eventId?: string; date?: string } | undefined;
  CalendarEventDetail: { eventId: string };
  QualityHub: undefined;
  CrashReports: undefined;
  CrashReportDetail: { reportId: string };
  Feedback: undefined;
  FeedbackForm: { entryId?: string } | undefined;
  FeedbackDetail: { entryId: string };
  ReleaseNotes: undefined;
  PerformanceMetrics: undefined;
  EnvironmentInfo: undefined;
  TestPlan: undefined;
  GovernanceHub: undefined;
  RoleMatrixV2: undefined;
  Departments: undefined;
  DepartmentForm: { departmentId?: string } | undefined;
  Regions: undefined;
  RegionForm: { regionId?: string } | undefined;
  PermissionsScreen: { role?: UserRoleExt } | undefined;
  Approvals: { status?: ApprovalStatus } | undefined;
  ApprovalDetail: { requestId: string };
  AuditLogV2: { resource?: PermissionResource; actorId?: string } | undefined;
  AuditDetail: { entryId: string };
  SessionLogs: { userId?: string } | undefined;
  SuspiciousLogins: undefined;
  KvkkAccessLogs: { subjectId?: string } | undefined;
  FieldHub: undefined;
  OfflineQueue: { status?: OfflineOpStatus } | undefined;
  OfflineOpDetail: { opId: string };
  ConflictResolver: { opId: string };
  SyncHistory: undefined;
  FieldFavorites: undefined;
  FieldSettings: undefined;
  AppUpdate: undefined;
  ConnectivityMonitor: undefined;
  BiHub: undefined;
  ExecutiveDashboard: undefined;
  DepartmentKpis: undefined;
  StaffPerformance: undefined;
  VehicleCostAnalysis: undefined;
  FuelConsumption: undefined;
  StockConsumption: undefined;
  QuoteWinLoss: undefined;
  CustomerProfitability: undefined;
  SlaTracking: undefined;
  RegionHeatmap: undefined;
  BudgetVsActual: undefined;
  ExecutiveSummary: undefined;
  PivotExport: undefined;
  EnterpriseIntegrationsHub: undefined;
  ErpConnections: undefined;
  ErpConnectionForm: { connectionId?: string } | undefined;
  ErpSyncJobs: undefined;
  ErpCustomers: undefined;
  ErpStock: undefined;
  ErpInvoiceDrafts: undefined;
  QuoteToOrder: undefined;
  CrmConnections: undefined;
  IntegrationWebhooks: undefined;
  IntegrationWebhookForm: { webhookId?: string } | undefined;
  IntegrationWebhookDeliveries: { webhookId?: string } | undefined;
  IntegrationApiKeys: undefined;
  ApiUsageLogs: undefined;
  IntegrationErrors: undefined;
  IntegrationHealth: undefined;
  PlatformHub: undefined;
  Tenants: undefined;
  TenantForm: { tenantId?: string } | undefined;
  TenantMembers: { tenantId?: string } | undefined;
  TenantSettings: { tenantId?: string } | undefined;
  Modules: undefined;
  Packages: undefined;
  Licenses: undefined;
  UsageLimits: undefined;
  DbIndexHints: undefined;
  ArchivePolicies: undefined;
  ArchiveJobs: undefined;
  Backups: undefined;
  RestoreTests: undefined;
  SystemHealth: undefined;
  MaintenanceMode: undefined;
  AiAssistantHub: undefined;
  AiPermissions: undefined;
  AiChat: { sessionId?: string } | undefined;
  CoPilot: undefined;
  AiKnowledgeBase: undefined;
  AiSessions: undefined;
  AiPozSuggest: undefined;
  AiQuoteDraft: undefined;
  AiQuoteDraftDetail: { draftId: string };
  AiWorkOrderSummary: undefined;
  AiCustomerInsight: undefined;
  AiRiskAlerts: undefined;
  AiDailyReport: undefined;
  AiUsageLogs: undefined;
  AgentConsole: { initialGoal?: string; autoStart?: boolean } | undefined;
  AgentSuggestions: undefined;
  FieldOpsHub: undefined;
  FieldToday: undefined;
  FieldShift: undefined;
  FieldJobs: undefined;
  FieldJobDetail: { jobId: string };
  FieldChecklist: { jobId: string };
  FieldQualityCheck: { jobId: string };
  FieldPerformance: undefined;
  FieldZones: undefined;
  FieldShiftPlan: undefined;
  FieldEmergency: undefined;
  FieldCommandCenter: undefined;
  SmartQuoteHub: undefined;
  SurveyForms: undefined;
  SurveyFormDetail: { surveyId: string };
  PozLibrary: undefined;
  PriceListVersions: undefined;
  QuoteCalculator: undefined;
  HvTransformerQuote: undefined;
  PeriodicCheckQuote: undefined;
  GesQuote: undefined;
  CompensationQuote: undefined;
  QuoteRevisionCompare: undefined;
  QuoteOutcomes: undefined;
  AiQuoteImprovements: undefined;
  LiveOpsHub: undefined;
  LiveOpsMap: undefined;
  JobHeatmap: undefined;
  PersonnelAvailability: undefined;
  SmartRouteSuggest: undefined;
  EtaEstimate: undefined;
  RouteDeviationAlerts: undefined;
  SiteEventLogs: undefined;
  TeamPerformanceLayer: undefined;
  OperationReplay: undefined;
  ComplianceHub: undefined;
  NonConformity: undefined;
  Capa: undefined;
  SafetyChecklists: undefined;
  RiskAssessment: undefined;
  AuditSchedule: undefined;
  AuditScoring: undefined;
  NcPhotoEvidence: undefined;
  NcAssignment: undefined;
  QualityDashboard: undefined;
  AuditReport: undefined;
  AssetHub: undefined;
  AssetList: undefined;
  AssetQr: { assetId?: string } | undefined;
  AssetMaintenanceHistory: { assetId?: string } | undefined;
  AssetFaultHistory: { assetId?: string } | undefined;
  WarrantyTracking: undefined;
  MaintenancePlan: undefined;
  MaintenanceAlerts: undefined;
  AssetCostAnalysis: undefined;
  EnergyAssetTypes: undefined;
  ServiceCard: { assetId?: string } | undefined;
  ExecHub: undefined;
  CeoSummary: undefined;
  OpsHealthScore: undefined;
  RevenueKpi: undefined;
  ProfitableCustomers: undefined;
  CostlyWorkOrders: undefined;
  EmployeeRanking: undefined;
  VehicleEfficiency: undefined;
  StockTurnover: undefined;
  QuoteConversion: undefined;
  AiExecSummary: undefined;
  CpHub: undefined;
  CpLogin: undefined;
  CpDashboard: undefined;
  CpQuoteApproval: undefined;
  CpWorkOrderTracking: undefined;
  CpServiceRequest: undefined;
  CpDocumentArchive: undefined;
  CpSatisfaction: undefined;
  CpNotifications: undefined;
  CpBranding: undefined;
  CpShareLinkSecurity: undefined;
  SecHub: undefined;
  SecClassification: undefined;
  KvkkRequests: undefined;
  DataExport: undefined;
  DataErasure: undefined;
  SecDevices: undefined;
  SuspiciousActivity: undefined;
  AdminAlerts: undefined;
  BackupReport: undefined;
  DrPlan: undefined;
  SecHealth: undefined;
  SaasHub: undefined;
  SaasTenants: undefined;
  SaasIsolation: undefined;
  SaasModules: undefined;
  SaasPackages: undefined;
  SaasLicenses: undefined;
  SaasUsageLimits: undefined;
  SaasBranding: undefined;
  SaasBilling: undefined;
  SaasSuperAdmin: undefined;
  SaasHealth: undefined;
  DepHub: undefined;
  DepSupabase: undefined;
  DepRlsPolicies: undefined;
  DepStorage: undefined;
  DepNetlify: undefined;
  DepBuildErrors: undefined;
  DepAiProviders: undefined;
  DepAiSecurity: undefined;
  DepWebWarnings: undefined;
  DepMobileWarnings: undefined;
  DepApkBuild: undefined;
  QaHub: undefined;
  QaConsole: undefined;
  QaUnused: undefined;
  QaShared: undefined;
  QaApiErrors: undefined;
  QaUiStates: undefined;
  QaTypes: undefined;
  QaModules: undefined;
  QaPerformance: undefined;
  QaQueries: undefined;
  QaReport: undefined;
  UatHub: undefined;
  UatAdmin: undefined;
  UatManager: undefined;
  UatField: undefined;
  UatCustomer: undefined;
  UatQuote: undefined;
  UatWorkOrder: undefined;
  UatStock: undefined;
  UatLocation: undefined;
  UatNotification: undefined;
  UatReport: undefined;
  DocHub: undefined;
  DocAdminGuide: undefined;
  DocManagerGuide: undefined;
  DocFieldGuide: undefined;
  DocCustomerGuide: undefined;
  DocSupabaseOps: undefined;
  DocNetlifyOps: undefined;
  DocApkOps: undefined;
  DocFaq: undefined;
  DocTraining: undefined;
  DocChecklist: undefined;
  GoLiveHub: undefined;
  GoLiveChecklist: undefined;
  GoLiveMonitor: undefined;
  GoLiveLogs: undefined;
  GoLiveFeedback: undefined;
  GoLiveBugTasks: undefined;
  GoLiveWeekly: undefined;
  GoLiveMonthly: undefined;
  GoLiveBacklog: undefined;
  GoLiveReleases: undefined;
  GoLiveSupport: undefined;
  CovHub: undefined;
  CovMatrix: undefined;
  CovCategory: { id: string };
  CovSummary: undefined;
  ExtHub: undefined;
  ExtConfig: { id: string };
  ExtLogs: { id: string };
  AdvHub: undefined;
  AdvEcommerce: undefined;
  AdvCallCenter: undefined;
  AdvBI: undefined;
  AdvVoiceAI: undefined;
  AdvCollectionForecast: undefined;
  AdvRfm: undefined;
  OrdHub: undefined;
  OrdList: undefined;
  OrdForm: { id?: string } | undefined;
  OrdDetail: { id: string };
  OrdRecurring: undefined;
  OrdAnalytics: undefined;
};

export type TabParamList = {
  Home: undefined;
  WorkOrders: undefined;
  NewService: undefined;
  Quotes: undefined;
  Manager: undefined;
};
