// AUTO-GENERATED by scripts/import-realdata.mjs — do not edit by hand.
import type { Employee } from '../types';

export const REAL_EMPLOYEES: Employee[] = [
  {
    "id": "emp-001-emrullah-gunay",
    "name": "Emrullah Günay",
    "role": "ELEKTRİK MÜHENDİSİ",
    "monthlyWage": 0,
    "dailyRate": 0,
    "attendance": {
      "Pzt": "Geldi",
      "Sal": "Geldi",
      "Çar": "Geldi",
      "Per": "Geldi",
      "Cum": "Geldi",
      "Cmt": "Gelmedi",
      "Paz": "Gelmedi"
    },
    "daysWorked": 5
  },
  {
    "id": "emp-002-ibrahim-ince",
    "name": "İBRAHİM İNCE",
    "role": "ELEKTRİK USTASI",
    "monthlyWage": 0,
    "dailyRate": 0,
    "attendance": {
      "Pzt": "Geldi",
      "Sal": "Geldi",
      "Çar": "Geldi",
      "Per": "Geldi",
      "Cum": "Geldi",
      "Cmt": "Gelmedi",
      "Paz": "Gelmedi"
    },
    "daysWorked": 5
  },
  {
    "id": "emp-003-recep-nurlu",
    "name": "RECEP NURLU",
    "role": "ELEKTRİK USTASI",
    "monthlyWage": 0,
    "dailyRate": 0,
    "attendance": {
      "Pzt": "Geldi",
      "Sal": "Geldi",
      "Çar": "Geldi",
      "Per": "Geldi",
      "Cum": "Geldi",
      "Cmt": "Gelmedi",
      "Paz": "Gelmedi"
    },
    "daysWorked": 5
  },
  {
    "id": "emp-004-mesut-arslan",
    "name": "Mesut Arslan",
    "role": "Elektrikçi",
    "monthlyWage": 0,
    "dailyRate": 0,
    "attendance": {
      "Pzt": "Geldi",
      "Sal": "Geldi",
      "Çar": "Geldi",
      "Per": "Geldi",
      "Cum": "Geldi",
      "Cmt": "Gelmedi",
      "Paz": "Gelmedi"
    },
    "daysWorked": 5
  },
  {
    "id": "emp-005-ibrahim-cagdas",
    "name": "İBRAHİM ÇAĞDAŞ",
    "role": "MAKİNA MÜHENDİS",
    "monthlyWage": 0,
    "dailyRate": 0,
    "attendance": {
      "Pzt": "Geldi",
      "Sal": "Geldi",
      "Çar": "Geldi",
      "Per": "Geldi",
      "Cum": "Geldi",
      "Cmt": "Gelmedi",
      "Paz": "Gelmedi"
    },
    "daysWorked": 5
  },
  {
    "id": "emp-006-alaattin-aktepe",
    "name": "ALAATTIN AKTEPE",
    "role": "ELEKTRİK USTASI",
    "monthlyWage": 0,
    "dailyRate": 0,
    "attendance": {
      "Pzt": "Geldi",
      "Sal": "Geldi",
      "Çar": "Geldi",
      "Per": "Geldi",
      "Cum": "Geldi",
      "Cmt": "Gelmedi",
      "Paz": "Gelmedi"
    },
    "daysWorked": 5
  },
  {
    "id": "emp-007-ahmet-cakir",
    "name": "AHMET ÇAKIR",
    "role": "ELEKTRİK USTASI",
    "monthlyWage": 0,
    "dailyRate": 0,
    "attendance": {
      "Pzt": "Geldi",
      "Sal": "Geldi",
      "Çar": "Geldi",
      "Per": "Geldi",
      "Cum": "Geldi",
      "Cmt": "Gelmedi",
      "Paz": "Gelmedi"
    },
    "daysWorked": 5
  },
  {
    "id": "emp-008-azad-nimetullah-balkin",
    "name": "AZAD NİMETULLAH BALKIN",
    "role": "Elektrikçi",
    "monthlyWage": 0,
    "dailyRate": 0,
    "attendance": {
      "Pzt": "Geldi",
      "Sal": "Geldi",
      "Çar": "Geldi",
      "Per": "Geldi",
      "Cum": "Geldi",
      "Cmt": "Gelmedi",
      "Paz": "Gelmedi"
    },
    "daysWorked": 5
  },
  {
    "id": "emp-009-gorkem-tanir",
    "name": "GÖRKEM TANIR",
    "role": "ELEKTRİK MÜHENDİSİ",
    "monthlyWage": 0,
    "dailyRate": 0,
    "attendance": {
      "Pzt": "Geldi",
      "Sal": "Geldi",
      "Çar": "Geldi",
      "Per": "Geldi",
      "Cum": "Geldi",
      "Cmt": "Gelmedi",
      "Paz": "Gelmedi"
    },
    "daysWorked": 5
  },
  {
    "id": "emp-010-ugur-gunes",
    "name": "UĞUR GÜNEŞ",
    "role": "KALFA",
    "monthlyWage": 0,
    "dailyRate": 0,
    "attendance": {
      "Pzt": "Geldi",
      "Sal": "Geldi",
      "Çar": "Geldi",
      "Per": "Geldi",
      "Cum": "Geldi",
      "Cmt": "Gelmedi",
      "Paz": "Gelmedi"
    },
    "daysWorked": 5
  },
  {
    "id": "emp-011-betul-bulbul",
    "name": "Betül Bülbül",
    "role": "EŞ",
    "monthlyWage": 0,
    "dailyRate": 0,
    "attendance": {
      "Pzt": "Geldi",
      "Sal": "Geldi",
      "Çar": "Geldi",
      "Per": "Geldi",
      "Cum": "Geldi",
      "Cmt": "Gelmedi",
      "Paz": "Gelmedi"
    },
    "daysWorked": 5
  },
  {
    "id": "emp-012-ufuk-gunes",
    "name": "UFUK GÜNEŞ",
    "role": "KALFA",
    "monthlyWage": 0,
    "dailyRate": 0,
    "attendance": {
      "Pzt": "Geldi",
      "Sal": "Geldi",
      "Çar": "Geldi",
      "Per": "Geldi",
      "Cum": "Geldi",
      "Cmt": "Gelmedi",
      "Paz": "Gelmedi"
    },
    "daysWorked": 5
  },
  {
    "id": "emp-013-yahya-yagiz",
    "name": "Yahya Yağız",
    "role": "Elektrikçi",
    "monthlyWage": 0,
    "dailyRate": 0,
    "attendance": {
      "Pzt": "Geldi",
      "Sal": "Geldi",
      "Çar": "Geldi",
      "Per": "Geldi",
      "Cum": "Geldi",
      "Cmt": "Gelmedi",
      "Paz": "Gelmedi"
    },
    "daysWorked": 5
  },
  {
    "id": "emp-014-mehmet-ali-ince",
    "name": "Mehmet Ali İNCE",
    "role": "ÇIRAK",
    "monthlyWage": 0,
    "dailyRate": 0,
    "attendance": {
      "Pzt": "Geldi",
      "Sal": "Geldi",
      "Çar": "Geldi",
      "Per": "Geldi",
      "Cum": "Geldi",
      "Cmt": "Gelmedi",
      "Paz": "Gelmedi"
    },
    "daysWorked": 5
  },
  {
    "id": "emp-015-emir-kayaoglu",
    "name": "Emir Kayaoğlu",
    "role": "ÇIRAK",
    "monthlyWage": 0,
    "dailyRate": 0,
    "attendance": {
      "Pzt": "Geldi",
      "Sal": "Geldi",
      "Çar": "Geldi",
      "Per": "Geldi",
      "Cum": "Geldi",
      "Cmt": "Gelmedi",
      "Paz": "Gelmedi"
    },
    "daysWorked": 5
  },
  {
    "id": "emp-016-emrah-kan-gurdag",
    "name": "Emrah Kan Gürdağ",
    "role": "ÇIRAK",
    "monthlyWage": 0,
    "dailyRate": 0,
    "attendance": {
      "Pzt": "Geldi",
      "Sal": "Geldi",
      "Çar": "Geldi",
      "Per": "Geldi",
      "Cum": "Geldi",
      "Cmt": "Gelmedi",
      "Paz": "Gelmedi"
    },
    "daysWorked": 5
  },
  {
    "id": "emp-017-hasan-basri-sezgi",
    "name": "HASAN BASRİ SEZGİ",
    "role": "Şoför",
    "monthlyWage": 0,
    "dailyRate": 0,
    "attendance": {
      "Pzt": "Geldi",
      "Sal": "Geldi",
      "Çar": "Geldi",
      "Per": "Geldi",
      "Cum": "Geldi",
      "Cmt": "Gelmedi",
      "Paz": "Gelmedi"
    },
    "daysWorked": 5
  },
  {
    "id": "emp-018-betul-bulbul",
    "name": "BETÜL BÜLBÜL",
    "role": "EŞ",
    "monthlyWage": 0,
    "dailyRate": 0,
    "attendance": {
      "Pzt": "Geldi",
      "Sal": "Geldi",
      "Çar": "Geldi",
      "Per": "Geldi",
      "Cum": "Geldi",
      "Cmt": "Gelmedi",
      "Paz": "Gelmedi"
    },
    "daysWorked": 5
  },
  {
    "id": "emp-019-huseyin-demir",
    "name": "Hüseyin Demir",
    "role": "avukat",
    "monthlyWage": 0,
    "dailyRate": 0,
    "attendance": {
      "Pzt": "Geldi",
      "Sal": "Geldi",
      "Çar": "Geldi",
      "Per": "Geldi",
      "Cum": "Geldi",
      "Cmt": "Gelmedi",
      "Paz": "Gelmedi"
    },
    "daysWorked": 5
  },
  {
    "id": "emp-020-mehmet-yanad",
    "name": "MEHMET YANAD",
    "role": "GÜNDELİKÇİ",
    "monthlyWage": 0,
    "dailyRate": 0,
    "attendance": {
      "Pzt": "Geldi",
      "Sal": "Geldi",
      "Çar": "Geldi",
      "Per": "Geldi",
      "Cum": "Geldi",
      "Cmt": "Gelmedi",
      "Paz": "Gelmedi"
    },
    "daysWorked": 5
  },
  {
    "id": "emp-021-oguz-samet-ugur",
    "name": "OĞUZ SAMET UĞUR",
    "role": "ÇIRAK",
    "monthlyWage": 0,
    "dailyRate": 0,
    "attendance": {
      "Pzt": "Geldi",
      "Sal": "Geldi",
      "Çar": "Geldi",
      "Per": "Geldi",
      "Cum": "Geldi",
      "Cmt": "Gelmedi",
      "Paz": "Gelmedi"
    },
    "daysWorked": 5
  },
  {
    "id": "emp-022-sercan-tener",
    "name": "SERCAN TENER",
    "role": "GÜNDELİKÇİ",
    "monthlyWage": 0,
    "dailyRate": 0,
    "attendance": {
      "Pzt": "Geldi",
      "Sal": "Geldi",
      "Çar": "Geldi",
      "Per": "Geldi",
      "Cum": "Geldi",
      "Cmt": "Gelmedi",
      "Paz": "Gelmedi"
    },
    "daysWorked": 5
  }
];
